export enum MAIN_PAGENATION {
  ANASAYFA = "ANASAYFA",
  INPUT_OLUSTUR = "INPUT_OLUSTUR",
  FORM_OLUSTUR = "FORM_OLUSTUR",
  ILETISIM = "ILETISIM",
  ADVENCE_JS = "ADVENCE_JS",
  TABLE = "TABLE",
  SELECT_LIST = "SELECT_LIST",
  PROJE = "PROJE"

}
